apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-vanilla
  namespace: argocd
spec:
  project: project-services
  sources:
    - repoURL: https://itzg.github.io/minecraft-server-charts/ 
      chart: minecraft
      targetRevision: 4.26.3
      helm:
        releaseName: minecraft-vanilla
        valueFiles:
          - $values/argocd/apps/services/values/minecraft-vanilla-values.yaml
    - repoURL: https://github.com/aryatavakoli/k8-homelab-charts
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minecraft
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true