apiVersion: v1
data:
  config.yml: |
    # This is a simplified config where the rest of the
    # settings are omitted and will be set by default.
    # See config.yml for the full configuration options.
    config:
      onlineMode: true
      lite:
        enabled: true
        routes:
          - host: 'mc.aryat.io'
            backend: minecraft-vanilla.minecraft.svc.cluster.local:25565
            modifyVirtualHost: true
          - host: 'mcm.aryat.io'
            backend: minecraft-modded.minecraft.svc.cluster.local:25565
            modifyVirtualHost: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: minekube-gate
  name: minekube-gate-configmap
  namespace: minecraft