apiVersion: v1
data:
  config.yml: |
    # This is a simplified config where the rest of the
    # settings are omitted and will be set by default.
    # See config.yml for the full configuration options.
    config:
      bind: 0.0.0.0:25565
      servers:
        vanillia: server-0.servers:25565
        # vanilla: minecraft-vanilla.minecraft.svc.cluster.local:25565
      try:
        - vanilla
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: minekube-gate
  name: minekube-gate-configmap
  namespace: minecraft