apiVersion: v1
data:
  config.yml: |
    # This is a simplified config where the rest of the
    # settings are omitted and will be set by default.
    # See config.yml for the full configuration options.
    config:
      lite:
        enabled: true
        routes:
          - host: '*'
            backend: minecraft-vanilla.minecraft.svc.cluster.local:25565
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: minekube-gate
  name: minekube-gate-configmap
  namespace: minecraft