minecraftServer:
  eula: true
  whitelist: "Sugogi,Bigggrice,Meeko__,Kath_potato,spalexma,Guojiaxi,fuzzywuzzy2233,foxrally,aleony14,japer111"
  clusterIP: None
  motd: "Welcome to Arya's Minecraft Server!"
persistence:
  dataDir: 
    enabled: true
    Size: 20Gi
  storageClass: "longhorn"
serviceAnnotations:
  external-dns.alpha.kubernetes.io/hostname: mc.aryat.io
  external-dns.alpha.kubernetes.io/target: dynamic.aryat.io
