image:
  tag: java21
minecraftServer:
  eula: true
  type: "FTBA"
  version: "1.21.1"
  ftbModpackId: "129"
  ftbModpackVersionId: "100168"
  whitelist: "Sugogi,Bigggrice,Meeko__,Kath_potato,spalexma,Guojiaxi,fuzzywuzzy2233,foxrally,aleony14,japer111"
  clusterIP: None
  motd: "Welcome to Arya's Modded Minecraft Server!"
persistence:
  dataDir: 
    enabled: true
    Size: 20Gi
  storageClass: "longhorn"
serviceAnnotations:
  external-dns.alpha.kubernetes.io/hostname: mcm.aryat.io
  external-dns.alpha.kubernetes.io/target: dynamic.aryat.io
livenessProbe: {}