minecraftServer:
  eula: true
  clusterIP: None
  type: "PAPER"
  version: "1.21.4"
serviceAnnotations:
  external-dns.alpha.kubernetes.io/hostname: mcm.aryat.io
  external-dns.alpha.kubernetes.io/target: dynamic.aryat.io