apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-services
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project:  project-services
  destination:
    namespace: argocd
    name: in-cluster
  source:
    path: argocd/apps/services
    repoURL: https://github.com/aryatavakoli/k8-homelab-charts
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true