apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jeopardy-app
  namespace: jeopardy-app
spec:
  parentRefs:
    - name: http-gateway
      sectionName: https-gateway
      namespace: gateway
      kind: Gateway
  hostnames:
  - jeopardy.aryat.io
  rules:
  - backendRefs:
    - name: jeopardy-app
      namespace: jeopardy-app
      port: 3000