apiVersion: v1
kind: Service
metadata:
  name: jeopardy-app
  namespace: jeopardy-app
spec:
  clusterIP: None
  ports:
  - name: jeopardy-app
    port: 3000
    targetPort: jeopardy-app
  selector:
    app: jeopardy-app